/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#9df5bd",
        "surface-bright": "#f6fbf4",
        "info-soft": "#4682B4",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#f6be3b",
        "on-primary-container": "#91e9b1",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#00522f",
        "primary": "hsl(var(--primary))",
        "surface-variant": "#dfe4dd",
        "on-surface-variant": "#3f4941",
        "on-secondary-container": "#6f5100",
        "off-white": "#FDFCFB",
        "secondary-fixed": "#ffdea0",
        "on-tertiary-container": "#ffc9c9",
        "outline": "#6f7a71",
        "surface-container-highest": "#dfe4dd",
        "surface-tint": "#046d40",
        "error-deep": "#8B0000",
        "on-secondary-fixed": "#261900",
        "surface-warm": "#F7F5F2",
        "warm-gold": "hsl(var(--accent))",
        "divider-gold": "hsla(var(--accent), 0.3)",
        "primary-container": "hsl(var(--primary))",
        "inverse-surface": "#2d322d",
        "on-primary-fixed": "#002110",
        "primary-fixed-dim": "#81d9a2",
        "brand-green": "hsl(var(--primary))",
        "brand-red": "hsl(var(--destructive))",
        "brand-gold": "hsl(var(--accent))",
        "charcoal-dark": "#1A1A1A",
        "on-tertiary-fixed-variant": "#7a2d33",
        "secondary": {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        "tertiary-fixed": "#ffdada",
        "muted-gray": "#666666",
        "on-secondary-fixed-variant": "#5c4300",
        "outline-variant": "#bec9bf",
        "on-error": "#ffffff",
        "surface-container": "#ebefe9",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#81d9a2",
        "on-tertiary-fixed": "#40010b",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eef2eb",
        "on-surface": "#181d19",
        "on-background": "#181d19",
        "tertiary": "#782b31",
        "secondary-container": "#fcc340",
        "error": "#ba1a1a",
        "surface": "#f6fbf4",
        "tertiary-container": "#964247",
        "background": "#f6fbf4",
        "success-muted": "#4C7F63",
        "surface-container-low": "#f1f5ee",
        "surface-dim": "#d7dbd5",
        "tertiary-fixed-dim": "#ffb3b4",
        "on-error-container": "#93000a",
        "surface-container-high": "#e5e9e3",
        // Keeping Shadcn defaults just in case
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      spacing: {
        "section-padding-desktop": "96px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "stack-md": "16px",
        "gutter": "24px",
        "section-padding-mobile": "40px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-md": ["Work Sans"],
        "meta": ["Public Sans"],
        "h3": ["Public Sans"],
        "h1": ["Public Sans"],
        "h2": ["Public Sans"],
        "body-lg": ["Work Sans"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "meta": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "h2": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}