export const ROLE_FILTER_OPTIONS: { label: string; value: string }[] = [
  { label: 'All Roles', value: '' },
  { label: 'Founder', value: 'FOUNDER' },
  { label: 'Executive', value: 'EXECUTIVE' },
  { label: 'Organizer', value: 'ORGANIZER' },
  { label: 'Movement Leader', value: 'MOVEMENT_LEADER' },
  { label: 'Super Admin', value: 'SUPER_ADMIN' },
  { label: 'Admin', value: 'ADMIN' },
  { label: 'Admin L2', value: 'ADMIN_L2' },
  { label: 'IT Manager', value: 'IT_MANAGER' },
  { label: 'Finance Officer', value: 'FINANCE_OFFICER' },
  { label: 'Regional Director', value: 'REGIONAL_DIRECTOR' },
  { label: 'Constituency Lead', value: 'CONSTITUENCY_LEAD' },
  { label: 'Base Diaspora Lead', value: 'BASE_DIASPORA_LEAD' },
  { label: 'Base Diaspora Secretary', value: 'BASE_DIASPORA_SECRETARY' },
  { label: 'Base Diaspora Treasurer', value: 'BASE_DIASPORA_TREASURER' },
  { label: 'Diaspora Affairs Officer', value: 'DIASPORA_AFFAIRS_OFFICER' },
  { label: 'Field Agent', value: 'FIELD_AGENT' },
  { label: 'Chief Editor', value: 'CHIEF_EDITOR' },
  { label: 'Senior Editor', value: 'SENIOR_EDITOR' },
  { label: 'Editor', value: 'EDITOR' },
  { label: 'Junior Editor', value: 'JUNIOR_EDITOR' },
  { label: 'Regional Correspondent', value: 'REGIONAL_CORRESPONDENT' },
  { label: 'Communications Officer', value: 'COMMUNICATIONS_OFFICER' },
  { label: 'Intelligence Analyst', value: 'INTELLIGENCE_ANALYST' },
  { label: 'Store Manager', value: 'STORE_MANAGER' },
  { label: 'Youth Leader', value: 'YOUTH_LEADER' },
]
