-- EXTENDED COUNTRIES DATA FOR THE BASE MOVEMENT
-- Execute this in your Supabase SQL Editor to populate the countries reference table.
-- This script uses 'ON CONFLICT (name) DO NOTHING' to prevent duplicates.

INSERT INTO countries (name, dialing_code, is_diaspora) VALUES
('Malaysia', '+60', true),
('Poland', '+48', true),
('Kenya', '+254', true),
('Thailand', '+66', true),
('Austria', '+43', true),
('United States', '+1', true),
('Israel', '+972', true),
('China', '+86', true),
('Senegal', '+221', true),
('Brazil', '+55', true),
('Nigeria', '+234', true),
('Sweden', '+46', true),
('Turkey', '+90', true),
('Australia', '+61', true),
('Ireland', '+353', true),
('Egypt', '+20', true),
('Kuwait', '+965', true),
('Luxembourg', '+352', true),
('Saudi Arabia', '+966', true),
('France', '+33', true),
('Burkina Faso', '+226', true),
('Germany', '+49', true),
('Norway', '+47', true),
('Mexico', '+52', true),
('Portugal', '+351', true),
('Japan', '+81', true),
('Netherlands', '+31', true),
('United Arab Emirates', '+971', true),
('South Africa', '+27', true),
('Russia', '+7', true),
('Tanzania', '+255', true),
('Qatar', '+974', true),
('Cameroon', '+237', true),
('Spain', '+34', true),
('United Kingdom', '+44', true),
('Canada', '+1', true),
('Italy', '+39', true),
('Switzerland', '+41', true),
('Belgium', '+32', true),
('Denmark', '+45', true),
('Finland', '+358', true),
('Greece', '+30', true),
('New Zealand', '+64', true),
('Singapore', '+65', true),
('South Korea', '+82', true),
('Ukraine', '+380', true),
('Vietnam', '+84', true)
ON CONFLICT (name) DO NOTHING;
