-- ===========================================================================
-- Apply the two pending uptime-monitoring migrations — 2026-08-05
--
-- WHY: vercel.json runs a daily cron against /api/uptime-check, which inserts
-- into public.site_uptime_checks. That table was never created, so every run
-- has been failing at the insert and the SLA Calculator page shows "unknown".
--
-- WHAT THIS RUNS (verbatim contents of the two pending migration files):
--   20260731141000_add_site_uptime_checks
--   20260731170000_allow_admin_uptime_summary_reads
--
-- It then records both versions in the migration history, so the history
-- stays accurate and `supabase db push` will not try to replay them.
--
-- SAFE TO RE-RUN: every statement is if-not-exists / drop-if-exists guarded,
-- and the history insert uses ON CONFLICT DO NOTHING.
--
-- AFTER RUNNING: confirm CRON_SECRET is set in the Vercel project env, or
-- /api/uptime-check returns 401 before it ever reaches the database.
-- ===========================================================================

-- --- 20260731141000_add_site_uptime_checks --------------------------------
create table if not exists public.site_uptime_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default timezone('utc', now()),
  target_url text not null,
  ok boolean not null,
  status_code integer,
  latency_ms integer,
  error_message text,
  checker text not null default 'vercel-cron',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists site_uptime_checks_checked_at_idx
  on public.site_uptime_checks (checked_at desc);

alter table public.site_uptime_checks enable row level security;

-- --- 20260731170000_allow_admin_uptime_summary_reads ----------------------
drop policy if exists "Admins can read site uptime checks" on public.site_uptime_checks;

create policy "Admins can read site uptime checks"
  on public.site_uptime_checks
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.admins
      where admins.id = auth.uid()
    )
  );

-- --- record both in the migration history ---------------------------------
insert into supabase_migrations.schema_migrations (version, name)
values
  ('20260731141000','add_site_uptime_checks'),
  ('20260731170000','allow_admin_uptime_summary_reads')
on conflict (version) do nothing;

-- --- verify ---------------------------------------------------------------
-- Expect: table_exists = 1, index_exists = 1, rls_enabled = true,
--         admin_policy = 1, recorded = 169
select
  (select count(*) from pg_tables
     where schemaname='public' and tablename='site_uptime_checks')            as table_exists,
  (select count(*) from pg_indexes
     where schemaname='public' and indexname='site_uptime_checks_checked_at_idx') as index_exists,
  (select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relname='site_uptime_checks')             as rls_enabled,
  (select count(*) from pg_policies
     where schemaname='public' and tablename='site_uptime_checks')            as admin_policy,
  (select count(*) from supabase_migrations.schema_migrations)                as recorded;
