-- Migration: Reconcile polling_stations constituency names with EC 2024 canonical names

DO $$ BEGIN
  UPDATE public.polling_stations SET constituency = 'Adansi Asokwa' WHERE lower(trim(constituency)) = lower('Adansi-Asokwa');
  UPDATE public.polling_stations SET constituency = 'Ahafo Ano South-East' WHERE lower(trim(constituency)) = lower('Ahafo Ano South East');
  UPDATE public.polling_stations SET constituency = 'Atwima Kwanwoma' WHERE lower(trim(constituency)) = lower('Atwima-Kwanwoma');
  UPDATE public.polling_stations SET constituency = 'Atwima Nwabiagya South' WHERE lower(trim(constituency)) = lower('Atwima-Nwabiagya South');
  UPDATE public.polling_stations SET constituency = 'Atwima Nwabiagya North' WHERE lower(trim(constituency)) = lower('Atwima-Nwabiagya North');
  UPDATE public.polling_stations SET constituency = 'Bosome Freho' WHERE lower(trim(constituency)) = lower('Bosome-Freho');
  UPDATE public.polling_stations SET constituency = 'Ejura Sekyedumase' WHERE lower(trim(constituency)) = lower('Ejura-Sekyedumase');
  UPDATE public.polling_stations SET constituency = 'Nsuta/Kwamang/Beposo' WHERE lower(trim(constituency)) = lower('Nsuta-Kwamang-Beposo');
  UPDATE public.polling_stations SET constituency = 'Effiduase/Asokore' WHERE lower(trim(constituency)) = lower('Effiduase-Asokore');
  UPDATE public.polling_stations SET constituency = 'Atebubu/Amantin' WHERE lower(trim(constituency)) = lower('Atebubu-Amantin');
  UPDATE public.polling_stations SET constituency = 'Abura Asebu Kwamankese' WHERE lower(trim(constituency)) = lower('Abura-Asebu-Kwamankese');
  UPDATE public.polling_stations SET constituency = 'Asikuma/Odoben/Brakwa' WHERE lower(trim(constituency)) = lower('Asikuma-Odoben-Brakwa');
  UPDATE public.polling_stations SET constituency = 'Awutu Senya East' WHERE lower(trim(constituency)) = lower('Awutu-Senya East');
  UPDATE public.polling_stations SET constituency = 'Awutu Senya West' WHERE lower(trim(constituency)) = lower('Awutu-Senya West');
  UPDATE public.polling_stations SET constituency = 'Ofoase/Ayirebi' WHERE lower(trim(constituency)) = lower('Ofoase-Ayirebi');
  UPDATE public.polling_stations SET constituency = 'Asene/Akroso/Manso' WHERE lower(trim(constituency)) = lower('Asene Akroso Manso');
  UPDATE public.polling_stations SET constituency = 'Nsawam/Adoagyiri' WHERE lower(trim(constituency)) = lower('Nsawam Adoagyiri');
  UPDATE public.polling_stations SET constituency = 'Anyaa/Sowutuom' WHERE lower(trim(constituency)) = lower('Anyaa-Sowutuom');
  UPDATE public.polling_stations SET constituency = 'Dome/Kwabenya' WHERE lower(trim(constituency)) = lower('Dome-Kwabenya');
  UPDATE public.polling_stations SET constituency = 'Dadekotopon' WHERE lower(trim(constituency)) = lower('Dade Kotopon');
  UPDATE public.polling_stations SET constituency = 'Ningo Prampram' WHERE lower(trim(constituency)) = lower('Ningo-Prampram');
  UPDATE public.polling_stations SET constituency = 'Yagaba/ Kubori' WHERE lower(trim(constituency)) = lower('Yagaba-Kubori');
  UPDATE public.polling_stations SET constituency = 'Tatale/Sanguli' WHERE lower(trim(constituency)) = lower('Tatale-Sanguli');
  UPDATE public.polling_stations SET constituency = 'Daboya / Mankarigu' WHERE lower(trim(constituency)) = lower('Daboya-Mankarigu');
  UPDATE public.polling_stations SET constituency = 'Yapei/Kusawgu' WHERE lower(trim(constituency)) = lower('Yapei-Kusawgu');
  UPDATE public.polling_stations SET constituency = 'Nadowli/Kaleo' WHERE lower(trim(constituency)) = lower('Nadowli-Kaleo');
  UPDATE public.polling_stations SET constituency = 'Daffiama/Bussie/Issa' WHERE lower(trim(constituency)) = lower('Daffiama-Bussie-Issa');
  UPDATE public.polling_stations SET constituency = 'Agotime Ziope' WHERE lower(trim(constituency)) = lower('Agotime-Ziope');
  UPDATE public.polling_stations SET constituency = 'Evalue Ajomoro Gwira' WHERE lower(trim(constituency)) = lower('Evalue-Ajomoro-Gwira');
  UPDATE public.polling_stations SET constituency = 'Tarkwa Nsuaem' WHERE lower(trim(constituency)) = lower('Tarkwa-Nsuaem');
  UPDATE public.polling_stations SET constituency = 'Sefwi Wiawso' WHERE lower(trim(constituency)) = lower('Sefwi-Wiawso');
  UPDATE public.polling_stations SET constituency = 'New Edubiase' WHERE lower(trim(constituency)) = lower('New Edubease');
  UPDATE public.polling_stations SET constituency = 'Manso Adubia' WHERE lower(trim(constituency)) = lower('Manso Edubia');
  UPDATE public.polling_stations SET constituency = 'Banda' WHERE lower(trim(constituency)) = lower('Banda Ahenkro');
  UPDATE public.polling_stations SET constituency = 'Ajumako Enyan Esiam' WHERE lower(trim(constituency)) = lower('Ajumako-Enyan-Essiam');
  UPDATE public.polling_stations SET constituency = 'Komenda Edina Eguafo Abrem' WHERE lower(trim(constituency)) = lower('Komenda-Edina-Eguafo-Abirem');
  UPDATE public.polling_stations SET constituency = 'Twifo Atti Morkwa' WHERE lower(trim(constituency)) = lower('Twifo-Atii Morkwaa');
  UPDATE public.polling_stations SET constituency = 'Akuapem South' WHERE lower(trim(constituency)) = lower('Akwapim South');
  UPDATE public.polling_stations SET constituency = 'Kwahu Afram Plains North' WHERE lower(trim(constituency)) = lower('Afram Plains North');
  UPDATE public.polling_stations SET constituency = 'Lower Manya Krobo' WHERE lower(trim(constituency)) = lower('Lower Manya');
  UPDATE public.polling_stations SET constituency = 'Upper Manya Krobo' WHERE lower(trim(constituency)) = lower('Upper Manya');
  UPDATE public.polling_stations SET constituency = 'Ayawaso West Wuogon' WHERE lower(trim(constituency)) = lower('Ayawaso West');
  UPDATE public.polling_stations SET constituency = 'Bortianor-Ngleshie Amanfro' WHERE lower(trim(constituency)) = lower('Bortianor-Ngleshie-Amanfrom');
  UPDATE public.polling_stations SET constituency = 'Madina' WHERE lower(trim(constituency)) = lower('Abokobi-Madina');
  UPDATE public.polling_stations SET constituency = 'Weija-Gbawe' WHERE lower(trim(constituency)) = lower('Weija');
  UPDATE public.polling_stations SET constituency = 'Nalerigu / Gambaga' WHERE lower(trim(constituency)) = lower('Nalerigu');
  UPDATE public.polling_stations SET constituency = 'Bole-Bamboi' WHERE lower(trim(constituency)) = lower('Bole');
  UPDATE public.polling_stations SET constituency = 'Bolga East' WHERE lower(trim(constituency)) = lower('Bolgatanga East');
  UPDATE public.polling_stations SET constituency = 'Essikadu-Ketan' WHERE lower(trim(constituency)) = lower('Essikado-Ketan');
END $$;
