create table if not exists public.site_uptime_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default timezone('utc', now()),
  target_url text not null,
  ok boolean not null,
  status_code integer,
  latency_ms integer,
  error_message text,
  checker text not null default 'vercel-cron',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists site_uptime_checks_checked_at_idx
  on public.site_uptime_checks (checked_at desc);

alter table public.site_uptime_checks enable row level security;
