insert into public.job_industries (id, name, sort_order) values
(1,'Technology & Digital Economy',1),
(2,'Finance, Banking & Accounting',2),
(3,'Engineering, Trades & Construction',3),
(4,'Healthcare & Allied Services',4),
(5,'Sales, Marketing & Retail',5),
(6,'Public Sector, Education & NGO',6),
(7,'Security Services',7)
on conflict (id) do update set name=excluded.name, sort_order=excluded.sort_order;

insert into public.job_sub_categories (id, industry_id, code, name, sort_order) values
(11,1,'1.1','Software & Web Development',1),
(12,1,'1.2','Data & Artificial Intelligence',2),
(13,1,'1.3','Cybersecurity & Cloud Infrastructure',3),
(14,1,'1.4','UI/UX & Product Design',4),
(15,1,'1.5','Digital Marketing & E-Commerce',5),
(21,2,'2.1','Core Accounting',1),
(22,2,'2.2','Banking Operations',2),
(23,2,'2.3','Financial Analysis & Advisory',3),
(24,2,'2.4','Payroll & Treasury',4),
(25,2,'2.5','Insurance',5),
(31,3,'3.1','Professional Engineering',1),
(32,3,'3.2','Project & Construction Management',2),
(33,3,'3.3','Skilled Trades (Electricians & Plumbers)',3),
(34,3,'3.4','Skilled Trades (Mechanics & Welders)',4),
(35,3,'3.5','General Construction Labor',5),
(41,4,'4.1','Clinical Professionals (Nurses & Midwives)',1),
(42,4,'4.2','Clinical Professionals (Doctors & Specialists)',2),
(43,4,'4.3','Allied Health Professionals',3),
(44,4,'4.4','Healthcare Support Staff',4),
(45,4,'4.5','Veterinary & Animal Health',5),
(51,5,'5.1','Sales & Business Development',1),
(52,5,'5.2','Retail & Store Operations',2),
(53,5,'5.3','Marketing & Brand Management',3),
(54,5,'5.4','Customer Service & Support',4),
(55,5,'5.5','Telemarketing & Telesales',5),
(61,6,'6.1','Teaching (Basic & Secondary Education)',1),
(62,6,'6.2','Tertiary & Vocational Education',2),
(63,6,'6.3','Government Administration',3),
(64,6,'6.4','Social Work & Community Development',4),
(65,6,'6.5','NGO & Development Sector',5),
(71,7,'7.1','Ghana Police Service',1),
(72,7,'7.2','Ghana Immigration Service',2),
(73,7,'7.3','Ghana National Fire Service',3),
(74,7,'7.4','Ghana Prisons Service',4),
(75,7,'7.5','Private Security',5)
on conflict (id) do update set industry_id=excluded.industry_id, code=excluded.code, name=excluded.name, sort_order=excluded.sort_order;

insert into public.job_roles (sub_category_id, name, sort_order)
select sc.id, v.name, v.sort
from (values
  ('1.1','Frontend Developer (React, Angular, Vue)',1),
  ('1.1','Backend Developer (Node.js, Python, PHP, .NET)',2),
  ('1.1','Mobile App Developer (Flutter, Kotlin, React Native)',3),
  ('1.1','Full-Stack Developer',4),
  ('1.1','WordPress / Wix Developer',5),
  ('1.2','Data Analyst (SQL, Power BI, Tableau)',1),
  ('1.2','Data Scientist (Python, R, Machine Learning)',2),
  ('1.2','Database Administrator (MySQL, PostgreSQL, MongoDB)',3),
  ('1.2','Business Intelligence Analyst',4),
  ('1.2','Data Engineer',5),
  ('1.3','Cybersecurity Analyst',1),
  ('1.3','Cloud Engineer (AWS, Azure, Google Cloud)',2),
  ('1.3','Network Administrator / Engineer',3),
  ('1.3','Systems Administrator',4),
  ('1.3','IT Support / Helpdesk Officer',5),
  ('1.4','UI Designer (Figma, Adobe XD, Sketch)',1),
  ('1.4','UX Researcher',2),
  ('1.4','Product Designer',3),
  ('1.4','Graphic Designer (Marketing focus)',4),
  ('1.4','Motion Graphics Designer',5),
  ('1.5','Social Media Manager',1),
  ('1.5','SEO Specialist',2),
  ('1.5','Content Creator / Content Strategist',3),
  ('1.5','E-commerce Manager (Shopify, WooCommerce)',4),
  ('1.5','Digital Marketing Coordinator',5),
  ('2.1','Accountant (General Ledger)',1),
  ('2.1','Auditor (Internal / External)',2),
  ('2.1','Financial Accountant',3),
  ('2.1','Tax Accountant',4),
  ('2.1','Management Accountant',5),
  ('2.2','Bank Teller',1),
  ('2.2','Customer Service Officer (Banking)',2),
  ('2.2','Credit Analyst',3),
  ('2.2','Relationship Officer',4),
  ('2.2','Branch Operations Manager',5),
  ('2.3','Financial Analyst (Corporate Finance)',1),
  ('2.3','Investment Analyst',2),
  ('2.3','Risk Analyst',3),
  ('2.3','Portfolio Manager',4),
  ('2.3','Personal Financial Advisor',5),
  ('2.4','Payroll Administrator',1),
  ('2.4','Treasury Officer',2),
  ('2.4','Accounts Payable Clerk',3),
  ('2.4','Accounts Receivable Clerk',4),
  ('2.4','Billing Specialist',5),
  ('2.5','Insurance Sales Agent',1),
  ('2.5','Underwriter',2),
  ('2.5','Claims Adjuster',3),
  ('2.5','Risk Surveyor',4),
  ('2.5','Actuarial Analyst',5),
  ('3.1','Civil Engineer (Roads, Buildings, Water)',1),
  ('3.1','Electrical Engineer (Power Systems)',2),
  ('3.1','Mechanical Engineer',3),
  ('3.1','Structural Engineer',4),
  ('3.1','Building Services Engineer (HVAC, Plumbing)',5),
  ('3.2','Construction Project Manager',1),
  ('3.2','Quantity Surveyor',2),
  ('3.2','Site Supervisor / Foreman',3),
  ('3.2','Construction Safety Officer',4),
  ('3.2','Building Inspector',5),
  ('3.3','Domestic Electrician (Homes / Offices)',1),
  ('3.3','Industrial Electrician (Factories / Sites)',2),
  ('3.3','Plumber - Residential Installation',3),
  ('3.3','Plumber - Commercial / Industrial',4),
  ('3.3','Solar Panel Installer',5),
  ('3.4','Motor Vehicle Mechanic (Cars)',1),
  ('3.4','Heavy Duty Mechanic (Trucks / Machinery)',2),
  ('3.4','Welder (Structural / Metal Fabrication)',3),
  ('3.4','Auto Electrician',4),
  ('3.4','Panel Beater / Sprayer',5),
  ('3.5','Mason / Block Layer',1),
  ('3.5','Carpenter (Formwork / Roofing)',2),
  ('3.5','Steel Fixer / Iron Worker',3),
  ('3.5','Painter / Decorator',4),
  ('3.5','Tiler (Floor / Wall Tiles)',5),
  ('4.1','Registered General Nurse (RGN)',1),
  ('4.1','Registered Midwife',2),
  ('4.1','Community Health Nurse (CHN)',3),
  ('4.1','Public Health Nurse',4),
  ('4.1','Theatre Nurse / Operating Room Nurse',5),
  ('4.2','Medical Officer (General Practice)',1),
  ('4.2','House Officer (Intern)',2),
  ('4.2','Medical Specialist (Surgeon, Pediatrician, etc.)',3),
  ('4.2','Physician Assistant / Medical Assistant',4),
  ('4.2','Dental Surgeon',5),
  ('4.3','Pharmacist',1),
  ('4.3','Medical Laboratory Scientist / Technician',2),
  ('4.3','Radiographer / Imaging Technologist',3),
  ('4.3','Physiotherapist',4),
  ('4.3','Nutritionist / Dietitian',5),
  ('4.4','Health Care Assistant / Nursing Assistant',1),
  ('4.4','Medical Records Officer',2),
  ('4.4','Pharmacy Technician',3),
  ('4.4','Health Information Clerk',4),
  ('4.4','Ambulance Technician / EMT',5),
  ('4.5','Veterinarian (Small / Large Animal)',1),
  ('4.5','Veterinary Nurse',2),
  ('4.5','Livestock Officer',3),
  ('4.5','Animal Health Technician',4),
  ('4.5','Pet Groomer / Kennel Assistant',5),
  ('5.1','Sales Representative (General)',1),
  ('5.1','Business Development Officer',2),
  ('5.1','Key Account Manager',3),
  ('5.1','Corporate Sales Executive',4),
  ('5.1','Field Sales Agent',5),
  ('5.2','Shop Sales Assistant',1),
  ('5.2','Store Manager',2),
  ('5.2','Cashier',3),
  ('5.2','Merchandiser',4),
  ('5.2','Inventory / Stock Clerk',5),
  ('5.3','Marketing Officer / Coordinator',1),
  ('5.3','Brand Manager',2),
  ('5.3','Marketing Communications Specialist',3),
  ('5.3','Market Research Analyst',4),
  ('5.3','Event Marketing Coordinator',5),
  ('5.4','Customer Service Representative (Call Center)',1),
  ('5.4','Receptionist / Front Desk Officer',2),
  ('5.4','Client Relations Officer',3),
  ('5.4','Contact Centre Agent',4),
  ('5.4','Helpdesk Support (Non-technical)',5),
  ('5.5','Telemarketer',1),
  ('5.5','Telesales Agent',2),
  ('5.5','Outbound Call Center Agent',3),
  ('5.5','Lead Generation Specialist',4),
  ('5.5','Customer Retention Specialist',5),
  ('6.1','Kindergarten / Early Childhood Teacher',1),
  ('6.1','Primary School Teacher',2),
  ('6.1','Junior High School (JHS) Teacher',3),
  ('6.1','Senior High School (SHS) Teacher',4),
  ('6.1','Special Education Teacher',5),
  ('6.2','University Lecturer',1),
  ('6.2','Polytechnic / Technical University Instructor',2),
  ('6.2','TVET Instructor (Technical / Vocational Trainer)',3),
  ('6.2','Research Assistant (University)',4),
  ('6.2','Workshop / Lab Technician (Educational)',5),
  ('6.3','Administrative Officer (Civil Service)',1),
  ('6.3','Executive Secretary',2),
  ('6.3','Records / Registry Officer',3),
  ('6.3','Protocol Officer',4),
  ('6.3','Human Resource Officer (Public Sector)',5),
  ('6.4','Social Worker',1),
  ('6.4','Community Development Officer',2),
  ('6.4','Youth Coordinator',3),
  ('6.4','Probation Officer',4),
  ('6.4','Child Protection Officer',5),
  ('6.5','Project Officer (NGO)',1),
  ('6.5','Monitoring & Evaluation (M&E) Officer',2),
  ('6.5','Grant Writer / Fundraising Officer',3),
  ('6.5','Field Coordinator (NGO)',4),
  ('6.5','Program Manager (NGO)',5),
  ('7.1','Police Constable (General Duty)',1),
  ('7.1','Police Officer (Graduate Entry)',2),
  ('7.1','Crime Investigator / CID Officer',3),
  ('7.1','Motor Traffic & Transport Officer (MTTD)',4),
  ('7.1','Police Communication / Dispatch Officer',5),
  ('7.2','Immigration Control Officer',1),
  ('7.2','Passport Office Officer',2),
  ('7.2','Border Patrol Officer',3),
  ('7.2','Immigration Investigator',4),
  ('7.2','Visa Processing Officer',5),
  ('7.3','Fire Fighter (Operational)',1),
  ('7.3','Fire Safety Officer / Inspector',2),
  ('7.3','Driver / Pump Operator',3),
  ('7.3','Fire Control Room Operator',4),
  ('7.3','Rescue Specialist',5),
  ('7.4','Prison Officer (General Duties)',1),
  ('7.4','Prisons Welfare Officer',2),
  ('7.4','Prisons Nurse (Clinical Staff)',3),
  ('7.4','Prisons Workshop Instructor (Skills Training)',4),
  ('7.4','Prisons Farm Supervisor',5),
  ('7.5','Security Guard (Residential / Commercial)',1),
  ('7.5','Security Supervisor',2),
  ('7.5','Close Protection Officer (Bodyguard)',3),
  ('7.5','CCTV Monitoring Officer',4),
  ('7.5','Security Patrol Driver',5)
) as v(code, name, sort)
join public.job_sub_categories sc on sc.code = v.code
on conflict (sub_category_id, name) do nothing;

-- Derived job level (heuristic from the role title; adjustable later).
update public.job_roles set level = case
  when name ~* '(Manager|Supervisor|Foreman|Director|\mHead\M)' then 'Management'
  when name ~* '(Assistant|Clerk|\mIntern\M|House Officer|Teller|Trainee|Cashier|\mGuard\M|Constable|Apprentice|Helpdesk|Groomer|Receptionist|\mEMT\M|Pump Operator|Control Room Operator|Dispatch)' then 'Entry'
  when name ~* '(Specialist|\mLead\M|Analyst|Engineer|Scientist|Architect|Consultant|Surgeon|Lecturer|Pharmacist|Underwriter|Auditor|Investigator|Inspector|Strategist|Researcher|Advisor|Adviser|Actuarial|Estimator|Quantity Surveyor)' then 'Senior / Specialist'
  else 'Professional'
end;
